name: CI pipeline

on:
  push:
    branches: [ main ]
  
jobs: 
  build: 
    runs-on: ubuntu-latest
    
    steps:  # This line was not properly indented
    - name: Checkout code
      uses: actions/checkout@v5

    - name: setup nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: install dependencies
      run: npm install

    - name: Run tests
      run: npm test